name: publish
on:
  push:
    branches:
      - main
jobs:
  pci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
            path: 'public'     
        uses: s0/git-publish-subdir-action@develop
        env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: public
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
